name: Build newifi3

on: 
  release:
    types: [published]
  workflow_dispatch:
#  push:
#    tags:
#    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 17 * * 4
#  watch:
#    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:22.04

    steps:
    - name: Install sudo package
      run: apt update && apt install sudo
    - name: nodejs
      run: |
        sudo apt-get update
        sudo apt-get -y install curl
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install 16.15.1
    - name: Checkout
      uses: actions/checkout@v3
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
    - name: Clone source code
      run: |
        cd toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: "newifi3"
      run: |
        cd trunk
        sudo ./build_firmware_modify newifi3
        sudo mv -f images/*.trx /opt/images/
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.R_TOKEN }}
        file: /opt/images/*.trx
        tag: AtuoBuild
        overwrite: true
        file_glob: true
